from abc import ABC, abstractmethod
from uuid import UUID

from kordevance.domain.models.profile import Profile


class ProfileRepo(ABC):
    @abstractmethod
    async def save(self, name: str, home_timezone: str, last_known_timezone: str) -> Profile: ...
    @abstractmethod
    async def delete(self, profile_id: UUID) -> None: ...
    @abstractmethod
    async def fetch(self, profile_id: UUID) -> Profile: ...
    @abstractmethod
    async def fetch_all(self) -> list[Profile]: ...

    @abstractmethod
    async def update(self, request: Profile) -> None: ...
    @abstractmethod
    async def delete_all(self) -> None: ...
    @abstractmethod
    async def update_timezone(self, profile_id: UUID, timezone: str) -> None: ...
    @abstractmethod
    async def fetch_timezone(self, profile_id: UUID) -> str | None: ...
